name: Gasandelec-StAlbans
favicon: null
layout_spectrum: 0.9079350146930665
typography_spectrum: 0.04126674588769674
title: Gas and Electricity Testing on 01727 350018  in St Albans www.gasandelec.uk
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75121389-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.16336098033934832
  lightness: 0.4028954291716218
  saturation: 0.20693241991102695
  rhythmicContrast: 0.9584733555093408
purpose: []
